// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQrp9ipLTFoCzNnLRhHQygn30VAHxSzE',
    appId: '1:685460687991:web:a45a859221f9fd7d564a72',
    messagingSenderId: '685460687991',
    projectId: 'smart-987d3',
    authDomain: 'smart-987d3.firebaseapp.com',
    databaseURL: 'https://smart-987d3-default-rtdb.firebaseio.com',
    storageBucket: 'smart-987d3.appspot.com',
    measurementId: 'G-31P35W0KNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMfddwmOwxLYYdIPDo_Cc0dd2ujvjp1A',
    appId: '1:685460687991:android:a8590af9312b9ae0564a72',
    messagingSenderId: '685460687991',
    projectId: 'smart-987d3',
    databaseURL: 'https://smart-987d3-default-rtdb.firebaseio.com',
    storageBucket: 'smart-987d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-ljbkunACGVIioYLYIFlpG9AuR9bINM',
    appId: '1:685460687991:ios:6e52fe451c10ab03564a72',
    messagingSenderId: '685460687991',
    projectId: 'smart-987d3',
    databaseURL: 'https://smart-987d3-default-rtdb.firebaseio.com',
    storageBucket: 'smart-987d3.appspot.com',
    iosBundleId: 'com.example.smart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-ljbkunACGVIioYLYIFlpG9AuR9bINM',
    appId: '1:685460687991:ios:fd0d339b73945800564a72',
    messagingSenderId: '685460687991',
    projectId: 'smart-987d3',
    databaseURL: 'https://smart-987d3-default-rtdb.firebaseio.com',
    storageBucket: 'smart-987d3.appspot.com',
    iosBundleId: 'com.example.smart.RunnerTests',
  );
}
